/**
 * 업비트 원화 마켓 코인 한글명 사전 및 실시간 메타데이터 캐시
 */

const STATIC_COIN_NAMES = {
  'BTC': '비트코인',
  'ETH': '이더리움',
  'XRP': '리플',
  'SOL': '솔라나',
  'DOGE': '도지코인',
  'ADA': '에이다',
  'AVAX': '아발란체',
  'DOT': '폴카닷',
  'NEAR': '니어프로토콜',
  'STX': '스택스',
  'SUI': '수이',
  'SHIB': '시바이누',
  'PEPE': '페페',
  'LINK': '체인링크',
  'ETC': '이더리움클래식',
  'BCH': '비트코인캐시',
  'SEI': '세이',
  'SAND': '샌드박스',
  'AXS': '엑시인피니티',
  'MANA': '디센트럴랜드',
  'FLOW': '플로우',
  'EOS': '이오스',
  'TRX': '트론',
  'XLM': '스텔라루멘',
  'VET': '비체인',
  'NEO': '네오',
  'GAS': '가스',
  'QTUM': '퀀텀',
  'HBAR': '헤데라',
  'ALGO': '알고랜드',
  'ICP': '인터넷컴퓨터',
  'APT': '앱토스',
  'POL': '폴리곤',
  'WAVES': '웨이브',
  'KNC': '카이버네트워크',
  'ZRX': '제로엑스',
  'CHZ': '칠리즈',
  'ENJ': '엔진코인',
  'BAT': '베이직어텐션토큰',
  'STORJ': '스토리지',
  'SC': '시아코인',
  'ANKR': '앵커',
  'GLM': '골렘',
  'WAXP': '왁스',
  'POWR': '파워렛저',
  'STRAX': '스트라티스',
  'MOC': '모스코인',
  'TT': '썬더코어',
  'IQ': '아이큐',
  'CRE': '캐리프로토콜',
  'MED': '메디블록',
  'DKA': '디카르고',
  'AHT': '아하토큰',
  'META': '메타디움',
  'FCT2': '피르마체인',
  'CBK': '코박토큰',
  'HUM': '휴먼스케이프',
  'DVI': '디비전',
  'MILK': '밀크',
  'AERGO': '아르고',
  'BORA': '보라',
  'AQT': '알파쿼크',
  'MVL': '엠블',
  'TON': '토카막네트워크',
  'STPT': '에스티피',
  'CRO': '크로노스',
  'T': '쓰레스홀드',
  'PUNDIX': '펀디엑스',
  'CELO': '셀로',
  'ELF': '엘프',
  'CVC': '시빅',
  'ARDR': '아더',
  'HIVE': '하이브',
  'KAVA': '카바',
  'STMX': '스톰엑스',
  'HUNT': '헌트',
  'ATOM': '코스모스',
  'XTZ': '테조스',
  'ZIL': '질리카',
  'IOST': '아이오에스티',
  'ICX': '아이콘',
  'THETA': '쎄타토큰',
  'TFUEL': '쎄타퓨엘',
  'MTL': '메탈',
  'UPP': '센티넬프로토콜',
  'BLUR': '블러',
  'BIGTIME': '빅타임',
  'ID': '스페이스아이디',
  'CYBER': '사이버',
  'ARKM': '아크엠',
  'PENDLE': '펜들',
  'ONDO': '온도파이낸스',
  'G': '그래비티',
  'UXLINK': '유엑스링크',
  'CARV': '카브',
  'SAFE': '세이프',
  'MOVE': '무브',
  'KAIA': '카이아',
  'TIA': '셀레스티아',
  'W': '웜홀',
  'JUP': '주피터',
  'DRIFT': '드리프트',
  'ZRO': '레이어제로',
  'BLAST': '블라스트',
  'TAO': '비텐서',
  'AAVE': '에이브',
  'UNI': '유니스왑',
  'CRV': '커브',
  'MINA': '미나',
  'ASTR': '아스타',
  'HIFI': '하이파이',
  'GMT': '스테픈',
  'AUCTION': '바운스토큰',
  'ZKP': '팬서',
  'ME': '매직에덴',
  'VIRTUAL': '버추얼프로토콜',
  'ENA': '에테나',
  'ENS': '이더리움네임서비스',
  'ZK': '지케이싱크',
  'ZKC': '바운드리스',
  'FOLD': '매니폴드',
  'ORCA': '오르카',
  'BONK': '봉크',
  'RVN': '레이븐코인',
  'MANTRA': '만트라',
  '1INCH': '1인치네트워크',
  'AERGO': '아르고',
  'AGLD': '어드벤처골드',
  'ALICE': '앨리스',
  'ANKR': '앵커',
  'ARK': '아크',
  'ASTR': '아스타',
  'AUDIO': '오디우스',
  'AXS': '엑시인피니티',
  'BAT': '베이직어텐션토큰',
  'BCH': '비트코인캐시',
  'BEAM': '빔',
  'BETA': '베타파이낸스',
  'BICO': '바이코노미',
  'BLUR': '블러',
  'BNT': '뱅코르',
  'BORA': '보라',
  'BSV': '비트코인에스브이',
  'BTC': '비트코인',
  'BTG': '비트코인골드',
  'BTT': '비트토렌트',
  'C98': '코인98',
  'CELO': '셀로',
  'CHZ': '칠리즈',
  'COMP': '컴파운드',
  'CRO': '크로노스',
  'CRV': '커브',
  'CTC': '크레딧코인',
  'CVC': '시빅',
  'CVX': '컨벡스파이낸스',
  'CYBER': '사이버',
  'DAI': '다이',
  'DOGE': '도지코인',
  'DOT': '폴카닷',
  'DYDX': '디와이디엑스',
  'EGLD': '멀티버스엑스',
  'ELF': '엘프',
  'ENJ': '엔진코인',
  'ENS': '이더리움네임서비스',
  'EOS': '이오스',
  'ETC': '이더리움클래식',
  'ETH': '이더리움',
  'FCT2': '피르마체인',
  'FET': '인공지능얼라이언스',
  'FIL': '파일코인',
  'FLOW': '플로우',
  'FXS': '프랙스셰어',
  'G': '그래비티',
  'GAL': '갤럭시',
  'GALA': '갈라',
  'GAS': '가스',
  'GLM': '골렘',
  'GMT': '스테픈',
  'GMX': '지엠엑스',
  'GRT': '더그래프',
  'HBAR': '헤데라',
  'HIFI': '하이파이',
  'HIVE': '하이브',
  'HUNT': '헌트',
  'ICP': '인터넷컴퓨터',
  'ICX': '아이콘',
  'ID': '스페이스아이디',
  'ILV': '일루비움',
  'IMX': '이뮤터블엑스',
  'INJ': '인젝티브',
  'IOST': '아이오에스티',
  'IOTA': '아이오타',
  'IOTX': '아이오텍스',
  'IQ': '아이큐',
  'JASMY': '재스미코인',
  'JST': '저스트',
  'JTO': '지토',
  'JUP': '주피터',
  'KAVA': '카바',
  'KLAY': '클레이튼',
  'KNC': '카이버네트워크',
  'KSM': '쿠사마',
  'LDO': '라이도다오',
  'LINK': '체인링크',
  'LOOKS': '룩스레어',
  'LSK': '리스크',
  'LTC': '라이트코인',
  'MANA': '디센트럴랜드',
  'MASK': '마스크네트워크',
  'MATIC': '폴리곤',
  'MBX': '마브렉스',
  'MBL': '무비블록',
  'MED': '메디블록',
  'MINA': '미나',
  'MKR': '메이커',
  'MLK': '밀크',
  'MNT': '만타네트워크',
  'MOC': '모스코인',
  'NEAR': '니어프로토콜',
  'NEO': '네오',
  'NKN': '엔케이엔',
  'NMR': '뉴메레르',
  'OCEAN': '오션프로토콜',
  'OGN': '오리진프로토콜',
  'OMG': '오미세고',
  'ONDO': '온도파이낸스',
  'ONT': '온톨로지',
  'OP': '옵티미즘',
  'ORBS': '오브스',
  'OXT': '오키드',
  'PENDLE': '펜들',
  'PEPE': '페페',
  'PLA': '플레이댑',
  'POL': '폴리곤',
  'POLYX': '폴리매쉬',
  'POWR': '파워렛저',
  'PYTH': '피스네트워크',
  'QTUM': '퀀텀',
  'RENDER': '렌더토큰',
  'RNDR': '렌더토큰',
  'ROSE': '오아시스',
  'RSR': '리저브라이트',
  'SAND': '샌드박스',
  'SC': '시아코인',
  'SEI': '세이',
  'SHIB': '시바이누',
  'SNX': '신세틱스',
  'SOL': '솔라나',
  'SSV': '에스에스브이나트워크',
  'STG': '스타게이트파이낸스',
  'STMX': '스톰엑스',
  'STORJ': '스토리지',
  'STPT': '에스티피',
  'STRAX': '스트라티스',
  'STRK': '스타크넷',
  'STX': '스택스',
  'SUI': '수이',
  'SUN': '썬',
  'SUSHI': '스시스왑',
  'SXP': '솔라',
  'T': '쓰레스홀드',
  'TAO': '비텐서',
  'THETA': '쎄타토큰',
  'TIA': '셀레스티아',
  'TON': '토카막네트워크',
  'TRB': '텔러',
  'TRX': '트론',
  'TFUEL': '쎄타퓨엘',
  'UMA': '우마',
  'UNI': '유니스왑',
  'UPP': '센티넬프로토콜',
  'USDT': '테더',
  'VET': '비체인',
  'VTHO': '비토르토큰',
  'W': '웜홀',
  'WAVES': '웨이브',
  'WAXP': '왁스',
  'WEMIX': '위믹스',
  'WLD': '월드코인',
  'XEC': '이캐시',
  'XEM': '넴',
  'XLM': '스텔라루멘',
  'XRP': '리플',
  'XTZ': '테조스',
  'YFI': '연파이낸스',
  'ZETA': '제타체인',
  'ZIL': '질리카',
  'ZRX': '제로엑스'
};

// 실시간 업비트 API에서 수집된 동적 사전 캐시
const dynamicCoinNames = new Map();

// 초기 정적 사전 등록
Object.entries(STATIC_COIN_NAMES).forEach(([symbol, nameKo]) => {
  dynamicCoinNames.set(symbol.toUpperCase(), nameKo);
  dynamicCoinNames.set(`KRW-${symbol.toUpperCase()}`, nameKo);
});

// 🔄 업비트 /v1/market/all 결과에서 한글명을 동적으로 캐시 등록
export function registerUpbitMarketList(markets = []) {
  if (!Array.isArray(markets)) return;
  markets.forEach(m => {
    if (m.market && m.korean_name) {
      const symbol = m.market.replace('KRW-', '').toUpperCase();
      dynamicCoinNames.set(symbol, m.korean_name);
      dynamicCoinNames.set(m.market.toUpperCase(), m.korean_name);
    }
  });
}

// 🌐 심볼 또는 마켓코드로 코인의 한글 이름 조회 (예: 'AUCTION' -> '바운스토큰', 'SAND' -> '샌드박스')
export function getCoinNameKo(marketOrSymbol) {
  if (!marketOrSymbol) return '';
  const clean = String(marketOrSymbol).trim().toUpperCase();
  const symbol = clean.replace('KRW-', '');
  
  if (dynamicCoinNames.has(symbol)) {
    return dynamicCoinNames.get(symbol);
  }
  if (dynamicCoinNames.has(clean)) {
    return dynamicCoinNames.get(clean);
  }
  return '';
}

// 🏷️ "AUCTION (바운스토큰)" 또는 "SAND (샌드박스)" 형식으로 포맷팅
export function formatCoinWithKo(marketOrSymbol) {
  if (!marketOrSymbol) return '';
  const symbol = String(marketOrSymbol).trim().toUpperCase().replace('KRW-', '');
  const nameKo = getCoinNameKo(symbol);
  if (nameKo && nameKo !== symbol) {
    return `${symbol} (${nameKo})`;
  }
  return symbol;
}
